security:
    enable_authenticator_manager: true   # ⭐ add this

    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                success_handler: App\Security\LoginSuccessHandler
            logout:
                path: app_logout
                target: /login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/back/users/dashboard, roles: [ROLE_ADMIN, ROLE_EMPLOYEE, ROLE_AGRICULTEUR, ROLE_FOURNISSEUR] }