security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                success_handler: App\Security\LoginSuccessHandler
            logout:
                path: app_logout
                target: /login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            custom_authenticators:
                - App\Security\GoogleAuthenticator
            entry_point: App\Security\GoogleAuthenticator
            user_checker: App\Security\AccountStatusChecker
    access_control:
        - { path: ^/back/admin, roles: ROLE_ADMIN }
        - { path: ^/semi-public/users/agriculteur, roles: ROLE_AGRICULTEUR }
        - { path: ^/semi-public/users/employe, roles: ROLE_EMPLOYEE }
        - { path: ^/semi-public/users/fournisseur, roles: ROLE_FOURNISSEUR }