when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            collect_serializer_data: false
            only_exceptions: true
            only_main_requests: true

when@test:
    framework:
        profiler: { collect: false }
