
parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    recaptcha_site_key: '%env(RECAPTCHA_SITE_KEY)%'
    recaptcha_secret_key: '%env(RECAPTCHA_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ResendMailer:
        class: App\Service\ResendMailer
        arguments:
            $apiKey: '%env(RESEND_API_KEY)%'

    App\Service\MimeTypeNamer:
        tags:
            - { name: vich_uploader.namer }
    App\Service\GeoIpService:
        arguments:
            $dbPath: '%kernel.project_dir%/config/geoip/GeoLite2-Country.mmdb'
    App\Service\FaceRecognitionService:
        arguments:
            $uploadDir:  '%kernel.project_dir%/public/uploads'
            $projectDir: '%kernel.project_dir%'