parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    gemini_api_key: '%env(GEMINI_API_KEY)%'
    # Ajout de la clé Mistral ici
    mistral_api_key: '%env(MISTRAL_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            # On lie les différentes clés API aux variables des constructeurs
            $huggingfaceToken: '%env(HUGGINGFACE_TOKEN)%'
            $mistralApiKey: '%env(MISTRAL_API_KEY)%'
            Knp\Snappy\GeneratorInterface: '@knp_snappy.pdf'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'